### ISSUE TITLE
issues with sonarquebe 7.7

### ISSUE THREAD

**Issue by rahulsharmamca** [EXXETA/sonar-msgflow-plugin#24]
I loaded the plugin in SonarQuebe 7.7 but the server failed to start,

java.lang.IllegalStateException: Fail to load plugin Msgflow [msgflow]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:571)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.getExtensions(MessageFlowPlugin.java:96)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.define(MessageFlowPlugin.java:87)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

**Comment by subashiniunny** [comment]
Same error with SonarQube 7.9.1 as well.

**Comment by shwetabhsuman12** [comment]
This is still not working on changing the build version to 7.9 .It is not even compiling.
With 6.7 it was able to compile .
Please suggest.

Error:
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[5,27] cannot find symbol
  symbol:   class Sensor
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[6,27] cannot find symbol
  symbol:   class SensorContext
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[10,27] cannot find symbol
  symbol:   class Issuable
  location: package org.sonar.api.issue
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[11,31] cannot find symbol
  symbol:   class Project
  location: package org.sonar.api.resources
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[25,42] cannot find symbol
  symbol: class Sensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[60,47] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.MessageMapSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[76,29] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.MessageMapSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MessageMapSensor.java:[76,43] cannot find symbol
  symbol:   class SensorContext
  location: class com.exxeta.iss.sonar.msgflow.batch.MessageMapSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[23,27] cannot find symbol
  symbol:   class Sensor
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[24,27] cannot find symbol
  symbol:   class SensorContext
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[28,27] cannot find symbol
  symbol:   class Issuable
  location: package org.sonar.api.issue
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[29,31] cannot find symbol
  symbol:   class Project
  location: package org.sonar.api.resources
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[43,44] cannot find symbol
  symbol: class Sensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[74,47] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.MQOutputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[87,29] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.MQOutputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQOutputNodeSensor.java:[87,43] cannot find symbol
  symbol:   class SensorContext
  location: class com.exxeta.iss.sonar.msgflow.batch.MQOutputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[21,27] cannot find symbol
  symbol:   class Sensor
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[22,27] cannot find symbol
  symbol:   class SensorContext
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[26,27] cannot find symbol
  symbol:   class Issuable
  location: package org.sonar.api.issue
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[27,31] cannot find symbol
  symbol:   class Project
  location: package org.sonar.api.resources
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[41,46] cannot find symbol
  symbol: class Sensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[80,47] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.IMSRequestNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[96,29] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.IMSRequestNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/IMSRequestNodeSensor.java:[96,43] cannot find symbol
  symbol:   class SensorContext
  location: class com.exxeta.iss.sonar.msgflow.batch.IMSRequestNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[22,27] cannot find symbol
  symbol:   class Sensor
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[23,27] cannot find symbol
  symbol:   class SensorContext
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[27,27] cannot find symbol
  symbol:   class Issuable
  location: package org.sonar.api.issue
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[28,31] cannot find symbol
  symbol:   class Project
  location: package org.sonar.api.resources
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[42,45] cannot find symbol
  symbol: class Sensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[74,47] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.SoapInputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[87,29] cannot find symbol
  symbol:   class Project
  location: class com.exxeta.iss.sonar.msgflow.batch.SoapInputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/SoapInputNodeSensor.java:[87,43] cannot find symbol
  symbol:   class SensorContext
  location: class com.exxeta.iss.sonar.msgflow.batch.SoapInputNodeSensor
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQHeaderNodeSensor.java:[3,27] cannot find symbol
  symbol:   class Sensor
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQHeaderNodeSensor.java:[4,27] cannot find symbol
  symbol:   class SensorContext
  location: package org.sonar.api.batch
[ERROR] /C:/sonar-msgflow-plugin-master (1)/src/main/java/com/exxeta/iss/sonar/msgflow/batch/MQHeaderNodeSensor.java:[8,27] cannot find symbol
